/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package en4.pkg10_ej4_detodosa;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class PorPrecio extends javax.swing.JInternalFrame {
private DefaultTableModel mod=new DefaultTableModel(){
    public boolean isCellEditable(int f,int c){
        return false;
    }
};

    /**
     * Creates new form PorPrecio
     */
    public PorPrecio() {
        initComponents();
        Cabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtvalor1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtvalor2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtlista = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Listado por precio");

        jLabel2.setText("Entre $:");

        jtvalor1.setText("0");
        jtvalor1.setToolTipText("");
        jtvalor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtvalor1KeyReleased(evt);
            }
        });

        jLabel3.setText("y");

        jtvalor2.setText("0");
        jtvalor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtvalor2ActionPerformed(evt);
            }
        });

        jtlista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtlista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtvalor1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtvalor1KeyReleased
        // TODO add your handling code here:
        borrarfilas();
        double v1=0;
        double v2=0;
        try{
        v1=Double.parseDouble(jtvalor1.getText());
        v2=Double.parseDouble(jtvalor2.getText());
        }catch(NumberFormatException x){
            System.out.println("Error "+x.getMessage());
        }
        for(Producto p:DeTodoSA.lista){
            if(p.getPrecio()>=v1 && p.getPrecio()<=v2){
                mod.addRow(new Object[]{
                    p.getCodigo(),
                    p.getDescripcion(),
                    p.getPrecio(),
                    p.getStock()
                });
            }
        }
//        for(Producto p:DeTodoSA.lista){
//            if(p.getPrecio()>Double.MIN_VALUE){
//                mod.addRow(new Object[]{
//                    p.getCodigo(),
//                    p.getDescripcion(),
//                    p.getPrecio(),
//                    p.getStock()
//                });
//            }
//        }
    }//GEN-LAST:event_jtvalor1KeyReleased

    private void jtvalor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtvalor2ActionPerformed
        // TODO add your handling code here:
        borrarfilas();
        double v1=0;
        double v2=0;
        try{
        v1=Double.parseDouble(jtvalor1.getText());
        v2=Double.parseDouble(jtvalor2.getText());
        }catch(NumberFormatException x){
            System.out.println("Error "+x.getMessage());
        }
        for(Producto p:DeTodoSA.lista){
            if(p.getPrecio()>=v1 && p.getPrecio()<=v2){
                mod.addRow(new Object[]{
                    p.getCodigo(),
                    p.getDescripcion(),
                    p.getPrecio(),
                    p.getStock()
                });
            }
        }
    }//GEN-LAST:event_jtvalor2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtlista;
    private javax.swing.JTextField jtvalor1;
    private javax.swing.JTextField jtvalor2;
    // End of variables declaration//GEN-END:variables

    private void Cabecera() {
        mod.addColumn("Codigo");
        mod.addColumn("Descripcion");
        mod.addColumn("Precio");
        mod.addColumn("Stock");
        jtlista.setModel(mod);
    }
    private void borrarfilas(){
    int filas=jtlista.getRowCount()-1;
    for(int f=filas;f>=0;f--){
        mod.removeRow(f);
    }
}
}
